name:                packageC
version:             0.1.0.0
license:             BSD3
author:              "Mike Pilgrem"
maintainer:          "public@pilgrem.com"
copyright:           "Copyright 2022 Mike Pilgrem"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  packageC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - packageC

tests:
  packageC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - packageC
    - packageA
